Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp, Source/Immutable/Public/Immutable/ImmutableSubsystem.h
Fixes for compile errors for UE 4.26
=> DX-2222: Fixed compile errors for UE4.26

Source/Immutable/Private/Immutable/Actions/ImtblPassportConnectEvmAsyncAction.cpp, Source/Immutable/Private/Immutable/Actions/ImtblPassportZkEvmGetBalanceAsyncAction.cpp, Source/Immutable/Private/Immutable/Actions/ImtblPassportZkEvmRequestAccountsAsyncAction.cpp, Source/Immutable/Private/Immutable/ImmutablePassport.cpp, Source/Immutable/Public/Immutable/Actions/ImtblPassportConnectEvmAsyncAction.h, Source/Immutable/Public/Immutable/Actions/ImtblPassportConnectSilentAsyncAction.h, Source/Immutable/Public/Immutable/Actions/ImtblPassportZkEvmGetBalanceAsyncAction.h, Source/Immutable/Public/Immutable/Actions/ImtblPassportZkEvmRequestAccountsAsyncAction.h, Source/Immutable/Public/Immutable/ImmutablePassport.h, Source/Immutable/Public/Immutable/ImmutableSubsystem.h
Create blueprints for ZkEvm connect, get balance, and request accounts.
=> feat: add zkevm connect, balance, and request accounts support 

Source/Immutable/Private/Immutable/Actions/ImtblPassportImxBatchNftTransferAsyncAction.cpp, Source/Immutable/Private/Immutable/Actions/ImtblPassportImxTransferAsyncAction.cpp, Source/Immutable/Private/Immutable/ImmutablePassport.cpp, Source/Immutable/Public/Immutable/Actions/ImtblPassportImxBatchNftTransferAsyncAction.h, Source/Immutable/Public/Immutable/Actions/ImtblPassportImxTransferAsyncAction.h, Source/Immutable/Public/Immutable/ImmutablePassport.h, Source/Immutable/Public/Immutable/ImmutableSubsystem.h
Added following StarkEx functionalities
- Transfer
- BatchNftTtansfer
Tiny bit of clean up.
=> DX-2224: Added StarkEx Transfer functionality

Immutable.uplugin, Source/Immutable/Immutable.Build.cs, Source/Immutable/Immutable_UPL_Android.xml, Source/Immutable/Private/Immutable/Actions/ImtblPassportConnectPKCEAsyncAction.cpp, Source/Immutable/Private/Immutable/Android/ImmutableAndroidJNI.cpp, Source/Immutable/Private/Immutable/Android/ImmutableAndroidJNI.h, Source/Immutable/Private/Immutable/ImmutablePassport.cpp, Source/Immutable/Public/Immutable/Actions/ImtblPassportConnectPKCEAsyncAction.h, Source/Immutable/Public/Immutable/ImmutablePassport.h
SDK now supports Android connectivity via PKCE flow on Unreal Engine 5.2
Docs will updated in another PR
=> feat: connect pkce for android ue 5.2

Source/Immutable/Immutable.Build.cs, Source/Immutable/Private/Immutable/Actions/ImtblPassportConnectPKCEAsyncAction.cpp, Source/Immutable/Private/Immutable/IOS/ImmutableIOS.cpp, Source/Immutable/Private/Immutable/IOS/ImmutableIOS.h, Source/Immutable/Private/Immutable/ImmutablePassport.cpp, Source/Immutable/Public/Immutable/ImmutablePassport.h
* Support iOS PKCE for UE 5.2
* Replace spaces in PKCE auth URL with '+'
=> feat: ios pkce ue 5.2

README.md
Fixed link to register application docs
=> docs: fix register app link

Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Fixed issue with reading null strings in Error Logging.
=> DX-2227: Added better error logging

README.md, Source/Immutable/Private/Immutable/Mac/ImmutableMac.cpp
* Updated README to include PKCE set up for MacOS
* Updated MacOS `presentationAnchorForWebAuthenticationSession` implementation
=> docs: macos pkce

Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp, Source/Immutable/Public/Immutable/ImmutableSubsystem.h
Fix for the plugin compile issues which occurred for Unreal Engine version 5.3 and higher.
#50 #46
=> [DX-2577] fix: added ue version condition for delegate instance type

.github/pull_request_template.md
Added public docs as a requirement for PRs
N/A
N/A
N/A
=> chore: add docs requirement to pull_request_template.md

Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Added device model info for the game bridge analytics
=> [DX-2669] feat: added device model info for bridge analytics

.github/workflows/update-version.yml, Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Add the Unreal SDK Tag version to analytics.
Added the Unreal SDK Tag version to analytics.
No other code changes
=> feat: [DX-2897]: add engine sdk version

Source/Immutable/Private/Immutable/ImmutableDataTypes.cpp, Source/Immutable/Private/Immutable/ImmutablePassport.cpp, Source/Immutable/Private/Immutable/ImmutableRequests.cpp, Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp, Source/Immutable/Private/Immutable/ImtblBrowserWidget.cpp, Source/Immutable/Public/Immutable/ImmutableRequests.h, Source/Immutable/Public/Immutable/ImmutableSubsystem.h, Source/Immutable/Public/Immutable/ImtblJSMessages.h
- Fixed text format issues 
- Method template function definition to a header file
- Added missing include header file
=>  [DX-1939] fixed compiler errors encountered in unreal engine 5.4

Source/Immutable/Public/Immutable/ImmutableDataTypes.h
=> chore: updated unreal sdk version

.github/workflows/tag.yml
Fix Create Tag workflow as the path to the `ImmutableDataTypes` is incorrect.
=> ci: update tag.yml

Source/Experimental/ImmutablezkEVMAPI/Private/APIMetadataApi.cpp, Source/Experimental/ImmutablezkEVMAPI/Private/APIMetadataApiOperations.cpp, Source/Experimental/ImmutablezkEVMAPI/Private/APIMetadataSearchApi.cpp, Source/Experimental/ImmutablezkEVMAPI/Private/APIMetadataSearchApiOperations.cpp, Source/Experimental/ImmutablezkEVMAPI/Private/APIPricingApiOperations.cpp, Source/Experimental/ImmutablezkEVMAPI/Public/APIMetadataApi.h, Source/Experimental/ImmutablezkEVMAPI/Public/APIMetadataApiOperations.h, Source/Experimental/ImmutablezkEVMAPI/Public/APIMetadataSearchApi.h, Source/Experimental/ImmutablezkEVMAPI/Public/APIMetadataSearchApiOperations.h, Source/Experimental/ImmutablezkEVMAPI/Public/APIPricingApiOperations.h, Source/Experimental/ImmutablezkEVMAPI/openapi.json
Updated zkEVM API to use renamed search API
=> chore: updated zkevm api

.github/workflows/branch-name.yml
Modified branch name workflow script
=> chore: removed requirement of folder name in branch name

.github/workflows/branch-name.yml, Source/Immutable/Immutable.Build.cs, Source/Immutable/Private/Immutable/Transak/TransakWebBrowser.cpp, Source/Immutable/Public/Immutable/Transak/TransakWebBrowser.h
Add Blu Web Browser to Transak Widget
Other miscellaneous clean up and refactor
=> add 4.26 support to transak widget

.github/workflows/update-zkevm-api-package.yml
Fix Github Actions not being optimal
=> fix: github actions not being optimal (#3559)

Source/ImmutableMarketplace/Private/OnRamp/ImmutableMarketplaceOnRampWidget.cpp
Fix compile errors for 5.1 and greater (#3570)
=> fix: compile errors for 5.1 and greater (#3570)

.github/workflows/release.yml
Fixed the release workflow to ensure the correct tag is used during releases.
=> [DX-3616] ci: update release.yml

README.md
Added automated test reports to front page of repo.
=> chore: add automated test reports (#3659)

.github/scripts/check_team_membership.sh
Update check_team_membership.sh to use Passport team instead.
=> ci: update check_team_membership.sh
