immutable/unreal-immutable-sdk

.gitignore
Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp
Source/Immutable/Private/Immutable/ImtblBrowserUserWidget.cpp
Source/Immutable/Private/Immutable/ImtblBrowserWidget.cpp
Source/Immutable/Private/Immutable/ImtblBrowserWidget.h
Source/Immutable/Private/Immutable/ImtblJSConnector.cpp
Source/Immutable/Private/Immutable/ImtblJSConnector.h
Source/Immutable/Public/Immutable/ImmutableSubsystem.h

Get SDK to run on Android devices. This is for UE 5.2 only.
Changes required:
- Set up the game bridge after the game engine init loop completes instead of when the viewport is created
- Instead of waiting for a response for 'init' to come back from the bridge to signal that the browser is ready, use the page load completed event instead. This is because there is some delay in binding all `window.ue` functions/values (including `window.ue.jsconnector`).
- Android webview cannot be collapsed but needs to be at least 1px x 1 px. However, the Android webview is offscreen, so it doesn't overlap with the game.
- To persist the Android webview across levels, the user widget cannot be removed from the parent
- Enable DOM storage for Android webview so we can use localStorage

feat: android support for ue 5.2

---

Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp
Source/Immutable/Private/Immutable/ImtblBrowserUserWidget.cpp
Source/Immutable/Private/Immutable/ImtblBrowserWidget.cpp
Source/Immutable/Private/Immutable/ImtblBrowserWidget.h
Source/Immutable/Private/Immutable/ImtblJSConnector.cpp
Source/Immutable/Private/Immutable/ImtblJSConnector.h
Source/Immutable/Public/Immutable/ImmutableSubsystem.h

iOS support for Unreal 5.2.
Most changes are the same as Android, except:
* The file URL. It is `"file:///index.html"` instead of `"file://immutable/index.html"`
* RemoveFromParent implementation is the same as Windows and MacOS

feat: ios support for ue 5.2

---

Source/Immutable/Immutable_UPL_Android.xml
Source/Immutable/Private/Immutable/Android/ImmutableAndroidJNI.cpp
Source/Immutable/Private/Immutable/Android/ImmutableAndroidJNI.h
Source/Immutable/Private/Immutable/Android/Java/ImmutableAndroid.java
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Public/Immutable/ImmutablePassport.h

* Use Custom Chome Tabs when using PKCE flow for Android. If none of the browsers support Custom Tabs Service, it will fall to the external browser
* Refactored deeplink handling code for Android to use static functions instead of callback

feat: android pkce flow using custom tabs

---

Source/Immutable/Immutable_UPL_Android.xml
Source/Immutable/Private/Immutable/Android/Java/ImmutableAndroid.java

Proguard now includes `ImmutableAndroid` imports to prevent obfuscation when creating a release build

feat: add android code to proguard

---

Source/Immutable/Immutable.Build.cs
Source/Immutable/Private/Immutable/Actions/ImtblPassportConnectPKCEAsyncAction.cpp
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Private/Immutable/Mac/ImmutableMac.cpp
Source/Immutable/Private/Immutable/Mac/ImmutableMac.h
Source/Immutable/Public/Immutable/ImmutablePassport.h

* Add PKCE support for MacOS
* Could not reuse the existing ImmutableIOS implementation, so created a new file specifically for MacOS
* Updated how the SDK extracts the `state` and `code` from the deeplink so that it works on all platforms

feat: macos pkce support

---

Source/Immutable/Immutable_UPL_Android.xml
Source/Immutable/Private/Immutable/Android/ImmutableAndroidJNI.cpp
Source/Immutable/Private/Immutable/Android/ImmutableAndroidJNI.h
Source/Immutable/Private/Immutable/Android/Java/ImmutableAndroid.java
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Public/Immutable/ImmutablePassport.h

* Added Android Chrome Custom Tabs callback so the game knows if the user has closed the embedded browser before authenticating

feat: add android custom tabs dismiss listener for pkce flow

---

Source/Immutable/Private/ImmutableModule.cpp

When packaging a game and running the built file (eg. `endlessrun.exe`), it will crash as  `IPluginManager::Get().FindPlugin("WebBrowserWidget")` will be a nullptr.
How to test:
- Package the game and run

fixes crash when game is packaged as FindPlugin would return nullptr

---

.github/workflows/linter.yml

* We disable linters since we wish to use UE code formatting

ci: disable cpp, csharp and clang linters

---

Source/Immutable/Immutable_UPL_Android.xml
Source/Immutable/Private/Immutable/Android/Java/ImmutableAndroid.java
Source/Immutable/Private/Immutable/ImmutablePassport.cpp

* On newer Android versions, `onCustomTabsDismissed` is triggered before PKCE deeplink is triggered (by ~100ms). This means `PKCEResponseDelegate` will be set to null before the SDK can use it to notify the consumer of the PKCE result. So added a delay before calling `onCustomTabsDismissed`
* Updated Chrome Custom Tabs version

[DX-2540] fix: android custom tabs dismiss callback nullifing pkce response delegate

---

.github/pr-labeler/config.yml
.github/workflows/label-pr.yml
.github/workflows/release.yml
CHANGELOG.md
README.md

* Set up release workflow when a tag is pushed
* Label closed and merged PRs so release Github Action can build a change log
* Link CHANGELOG file to releases
* Remove change log section from README as it is now automated

ci: set up release github action

---

.github/workflows/branch-name.yml

Set up a GitHub Action to check pull request branch names so that the correct labels can be applied upon merge.

ci: check branch name

---

Source/Immutable/Immutable_UPL_Android.xml
Source/Immutable/Private/Immutable/Android/Java/CustomTabsController.java

* Refactor Android Custom Tabs implementation to not use lambdas
* Specify the Java version

refactor: android custom tabs to not use lambdas

---

Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Public/Immutable/ImmutablePassport.h

1. Sometimes, Android dismisses Chrome Custom Tabs before deeplink is triggered. When Chrome Custom Tabs is dismissed, `HandleOnLoginPKCEDismissed` is called.
2. There are two parts to the PKCE flow
i. Log into Passport in Chrome Custom Tabs. On success, deeplink the user back into the game.
ii. After deeplink is called, complete the PKCE login flow. On success, the PKCE login is complete.
Currently, `HandleOnLoginPKCEDismissed` checks if the SDK is currently trying to connect (using `IPS_CONNECTING`) and if it is, it will nullify `PKCEResponseDelegate`. This is not the right way to check, as `IPS_CONNECTING` is set when PKCE flow starts (point 2i), so if Custom Tabs is dismissed after the second part of PKCE login flow starts (point 2ii) but _before_ it finishes, the …

[DX-2615] fix: android custom tabs dismiss callback

---

Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Private/Immutable/ImmutableSaveGame.cpp
Source/Immutable/Private/Immutable/Mac/ImmutableMac.cpp
Source/Immutable/Public/Immutable/ImmutablePassport.h
Source/Immutable/Public/Immutable/ImmutableSaveGame.h

Resolved an issue with logout using device flow instead of pkce flow for players logged in via pkce flow
New save game object to save if player successfully logged in via pkce flow
Fixed incorrect behaviour of logout in case of relogin of pkce flow

[DX-2603] fix: add save game object to store immutable passport pkce connected

---

README.md

Aligned this readme and Immutable Unreal docs in terms of BLUI installation
Customers will have better information on how to install BLUI plugin for UE 4.26 and 4.27
README.md file

[DX-2602] fix: corrected blui plugin download link for ue 4.26

---

Source/Immutable/Private/Immutable/ImmutablePassport.cpp

Session that was previously logged in with PKCE flow fall back to PKCE login flow in the event of a relogin failure. The same behaviour is expected for connect with PKCE flow
Improves customer experience

[DX-2616] fix: failed login with cached session falls back to login pkce

---

Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp
Source/Immutable/Private/Immutable/ImtblBlui.cpp
Source/Immutable/Private/Immutable/ImtblBlui.h
Source/Immutable/Private/ImmutableModule.cpp

We added CEF message loop stop method before BLUI process closure. Also, we added a code that will forcefully close BLUI process if it still hangs. 
Improve memory performance on a game/app closure

[DX-2591] fix: adjusted blui process closure routines

---

Source/Immutable/Private/Immutable/ImmutableSubsystem.cpp

Fixed issue with non-BLUE builds

[DX-2616] fix: added blui macro for ue5 projects

---

Source/Immutable/Private/Immutable/Actions/ImtblPassportLogoutAsyncAction.cpp
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Public/Immutable/Actions/ImtblPassportLogoutAsyncAction.h
Source/Immutable/Public/Immutable/ImmutablePassport.h

The SDK's current logout function performs a local logout and also opens the browser to log them out of the browser session. However, some customers might find the browser popup undesirable. To address this issue, a change has been made to allow users to skip logging out of the browser step and only perform a local logout:
* To skip the Auth0 logout and only perform a local logout, set `DoHardLogout` to `false` when calling `Logout` method/blueprint node.
* To perform local and Auth0 logout, set the `DoHardLogout` parameter to `true` when calling the `Logout` method/blueprint node. This is the default.
Developers can now choose not to display the browser pop-up when logging out. However, if they choose this option, users will remain logged into Passport in the browser until the browser …

[DX-2716] feat: ability to skip logging out of auth0 in the browser

---

Source/Immutable/Private/Immutable/ImmutableDataTypes.cpp
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Private/Immutable/ImmutableRequests.cpp
Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Source/Immutable/Public/Immutable/ImmutablePassport.h
Source/Immutable/Public/Immutable/ImmutableResponses.h

- Removed unused faulty json data types
- Slightly modified load of passport settings (save game) routine
- Moved data types to dedicated source code files
Cleared Immutable log errors in the editor 
Fixes for misleading in-editor errors

[DX-2718, DX-2719] Removal of redundant data types. Passport save game load on initialisation.    

---

Source/Immutable/Private/Immutable/ImmutableDataTypes.cpp
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Private/Immutable/ImmutableRequests.cpp
Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Source/Immutable/Public/Immutable/ImmutablePassport.h
Source/Immutable/Public/Immutable/ImmutableResponses.h

- Removed unused faulty json data types
- Slightly modified load of passport settings (save game) routine
- Moved data types to dedicated source code files
Cleared Immutable log errors in the editor 
Fixes for misleading in-editor errors

[DX-2718, DX-2719] fix: removal of redundant data types, save game load on initialisation

---

Source/Immutable/Private/Immutable/ImmutableAnalytics.cpp
Source/Immutable/Private/Immutable/ImmutableAnalytics.h
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Public/Immutable/ImmutableNames.h
Source/Immutable/Public/Immutable/ImmutablePassport.h
Source/Immutable/Public/Immutable/ImtblJSConnector.h

- Added track analytics function to Unreal SDK
- Added tracking to Passport functions(initialise, login, connect and logout)
No impact

[DX-2828] feat: added analytics

---

.github/scripts/check_team_membership.sh
.github/workflows/release.yml
.github/workflows/tag.yml
.github/workflows/update-version.yml

- Update release.yml workflow to include TS SDK version used to build game bridge
- Fixed update-version.xml
- Added a tagging workflow that gets triggered once a release PR is merged. This tag workflow will then trigger the release workflow.

[DX-3037] ci: update release.yml

---

Source/Immutable/Private/Immutable/ImmutableAnalytics.cpp

Resolved a minor issue where an empty string was passed to the analytics instead of a properly formatted empty JSON object.

fix: json parsing issue with empty string

---

Source/Immutable/Private/Immutable/Actions/ImtblPassportInitializationAsyncAction.cpp
Source/Immutable/Public/Immutable/Actions/ImtblPassportInitializationAsyncAction.h
Source/Immutable/Public/Immutable/ImmutableDataTypes.h

[DX-3031](https://immutable.atlassian.net/browse/DX-3197)
Add silent logout option to Passport initialize blueprint node.
- Allows developers to select the silent logout method for Passport.
- `IsSilentLogout` switch to the Passport `init` blueprint node.
[DX-3031]: https://immutable.atlassian.net/browse/DX-3031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add silent logout to passport init blueprint

---

Source/Immutable/Private/Immutable/ImtblBlui.cpp
Source/Immutable/Public/Immutable/Actions/ImtblBlueprintAsyncAction.h
Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Source/Immutable/Public/Immutable/ImmutableSubsystem.h

Fixed issues with header files and added minor check for BLUI plugin

feat: minor improvements 

---

Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Source/Immutable/Public/Immutable/ImmutablePassport.h

Add documentation to passport methods

docs: add documentation to passport methods

---

Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Source/Immutable/Public/Immutable/ImmutablePassport.h

Add documentation to passport methods

docs: add documentation to passport methods (#3340)

---

Source/Immutable/Immutable.Build.cs
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Private/Immutable/ImmutableUtilities.cpp
Source/Immutable/Public/Immutable/ApplicationConfig.h
Source/Immutable/Public/Immutable/ImmutablePassport.h
Source/Immutable/Public/Immutable/ImmutablePluginSettings.h
Source/Immutable/Public/Immutable/ImmutableUtilities.h

Added helper class for application configuration.  UApplicationConfig stores configuration settings such as URLs, chain names, contract addresses, client IDs, and environment settings for the zkEVM API, Orderbook API, and Passport. A new settings and utility classes help to retrieve the application config data efficiently.

feat: added application configuration utilities

---

Immutable.uplugin
Source/Immutable/Immutable.Build.cs
Source/Immutable/Private/Immutable/ImtblBlui.cpp
Source/Immutable/Private/Immutable/Tests/ImtblMessagesTest.cpp
Source/ImmutablePluginManager/ImmutablePluginManager.Build.cs
Source/ImmutablePluginManager/Private/ImmutablePluginManager.cpp
Source/ImmutablePluginManager/Public/ImmutablePluginManager.h

We've introduced a plugin manager module that automatically switches between the BLUI and Epic's WebBrowserWidget plugins at build time. This eliminates the need for developers to manually disable either plugin by editing the .uplugin file, streamlining the installation process.
If you encounter a popup error indicating missing BLUI or WebBrowserWidget modules while running the editor, please try rerunning or rebuilding your project.

Getting CICD Online

---

.github/workflows/update-zkevm-api-package.yml
Source/ImmutablezkEVMAPI/openapi-generator/batch-files/generate.sh

Automate the process of updating zkEVM repo when it's corresponding openapi changes.
A cron job is scheduled to run every day at 10 AM.
A pull request will be created automatically whenever new changes are detected.

Automate the process of updating zkEVM repo when it's corresponding openapi changes (#3497) 

---

Source/ImmutableMarketplace/Public/Bridge/ImmutableBridgeQueryParams.h
Source/ImmutableMarketplace/Public/OnRamp/ImmutableOnRampQueryParams.h
Source/ImmutableMarketplace/Public/Swap/ImmutableSwapQueryParams.h

Ensure queryparams are set to their correct default values

fix: ensure queryparams are set to their correct default values #3552

---

Source/ImmutableMarketplace/Private/OnRamp/ImmutableMarketplaceOnRampWidget.cpp
Source/ImmutableMarketplace/Public/OnRamp/ImmutableMarketplaceOnRampWidget.h

Fix inconsistent naming for for OnRampWidget

fix: inconsistent naming for for on ramp widget (#3555)

---

.github/workflows/update-version.yml

Update the "update version" GitHub Action workflow to use minor and patch inputs instead of requiring a manually entered version string.
- Handles alpha versions correctly:
- Patch update: Converts `1.3.0.alpha` → `1.3.0` (removes `.alpha`).
- Minor update: Converts `1.3.0.alpha` → `1.4.0` (skips `1.3.0`).

[DX-3569] ci: update update-version.yml

---

.github/workflows/release.yml
.github/workflows/update-version.yml

This PR updates the GitHub Actions workflow to include a new "Mark as alpha release" checkbox. When selected, the updated version will have the `.alpha` suffix unless it already exists.
- Added a `mark_as_alpha` input (boolean checkbox).  
- Adjusted version bumping logic:  
- If **not marked as alpha**, `.alpha` is removed if present.  
- If **marked as alpha**, `.alpha` is added if not already present.  
- Ensured correct version increments for both **patch** and **minor** updates. 
Example:
| Current Version | Upgrade Type | Mark as Alpha | New Version |  
|----------------|-------------|---------------|-------------|  
| 1.3.0.alpha   | Patch       | No            | 1.3.0       |  
| 1.3.0.alpha   | Minor       | No            | 1.4.0       |  
| 1.3.0         | Patch       | No …

[DX-3571] ci: update version alpha

---

.github/workflows/release.yml

Updated the release workflow to use tags with the prefix 'v' when creating a release.

[DX-3616] ci: add v prefix to tag name when creating a release

---

Source/Immutable/Private/Immutable/Actions/ImtblConnectImxAsyncAction.cpp
Source/Immutable/Private/Immutable/ImmutableDataTypes.cpp
Source/Immutable/Private/Immutable/ImmutablePassport.cpp
Source/Immutable/Private/Immutable/Windows/ImmutablePKCEWindows.cpp
Source/Immutable/Public/Immutable/ImmutableDataTypes.h
Source/Immutable/Public/Immutable/ImmutableNames.h
Source/Immutable/Public/Immutable/ImmutablePassport.h
Source/Immutable/Public/Immutable/Windows/ImmutablePKCEWindows.h

Alpha release of PKCE for Windows support

chore: PKCE for Windows support (alpha release)

---

Source/Immutable/Private/Immutable/Mac/ImmutableMac.cpp
Source/Immutable/Private/Immutable/Mac/ImmutableMac.h

* Fix passport is nil during automated tests
* Add workaround to `ASWebAuthenticationSession` confirm dialog for automated tests. For automated test, pkce tests will use `launchUrlInBrowser` instead of `ASWebAuthenticationSession` as the confirm dialog can not be automated or skipped
Jira Ticket: [ID-3775](https://immutable.atlassian.net/browse/ID-3775)
[ID-3775]: https://immutable.atlassian.net/browse/ID-3775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ID-3775] chore: Migrate tests that use Device Code Auth to PKCE
